# Generated by Django 5.0 on 2023-12-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_questions_item"),
    ]

    operations = [
        migrations.RenameModel(old_name="Subsection", new_name="Subsections",),
        migrations.RenameField(
            model_name="items", old_name="subject", new_name="subsection",
        ),
    ]
